Lesson5  task
bagdenia/qna pull request #4
Opened 2017-05-24 19:44 UTC by bagdenia

2017-05-24 20:47 UTC, palkan-th requested changes

2017-05-24 20:47 UTC, palkan-th commented on app/controllers/answers_controller.rb
> +  def index
А нужен ли нам тут индекс?

2017-05-24 20:47 UTC, palkan-th commented on app/controllers/answers_controller.rb
> +    if current_user.id == @answer.user.id
Для сравнения нам достаточно id (и.е. user_id), а сейчас мы загружаем пользователя из базы.

2017-05-24 20:47 UTC, palkan-th commented on app/controllers/questions_controller.rb
> +    if current_user.id == @question.user.id
И здесь

2017-05-24 20:47 UTC, palkan-th commented on db/migrate/20170523202935_add_user_to_questions.rb
> +class AddUserToQuestions < ActiveRecord::Migration[5.1]
Что это за пустые миграции такие?

2017-05-24 20:47 UTC, palkan-th commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'Answer successfully deleted'
А проверить, что текста ответа нет на странице?

2017-05-24 20:47 UTC, palkan-th commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Question successfully deleted
Здесь нужно также проверить, что вопроса больше нет в списке

2017-05-24 20:47 UTC, palkan-th commented on spec/acceptance/show_question_spec.rb
> +    expect(page).to have_content question.answers.first.body
А второй ответ?
Для проверки отображения списка нужно проверить хотя бы два элемента.

Но тут есть подвох: сейчас фабрика создаёт ответы с одинаковым текстом, а для проверки надо разный текст.
Самое время внедрить гем faker в фабрики.

2017-05-24 20:47 UTC, palkan-th commented on spec/controllers/answers_controller_spec.rb
> +    before {question}
Вопрос можно и не вызывать здесь, он будет создан вместе с ответом.

2017-05-25 04:50 UTC, bagdenia commented on app/controllers/answers_controller.rb
> +  def index
конечно нет. забыла подчистить, пока пыталась разобраться с одним косяком чего только не перепробовала.

2017-05-25 05:18 UTC, bagdenia commented on db/migrate/20170523202935_add_user_to_questions.rb
> +class AddUserToQuestions < ActiveRecord::Migration[5.1]
ref забыла в r g AddUserToQuestions вместо AddUserRefToQuestions

2017-05-25 09:07 UTC, palkan-th commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_no_content 'answer_body'
`expect(page).to have_no_content answer_body` ?

2017-05-25 10:25 UTC, bagdenia commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_no_content 'answer_body'
что, так нельзя?

2017-05-25 21:30 UTC, webmstk commented on app/views/layouts/application.html.slim
> +    -if !user_signed_in?
`unless` хорошо здесь впишется

2017-05-25 21:30 UTC, webmstk commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_no_content 'answer_body'
не строка

2017-05-25 21:30 UTC, webmstk commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_no_content qstn_title
Кстати, а стоит ли выносить это в переменную? Используется один раз, читаемости не добавляет. Скорее наоборот.

2017-05-25 21:30 UTC, webmstk commented on spec/controllers/answers_controller_spec.rb
> +        sign_in user
На самом деле лучше пойти от обратного. Используем хелпер `sign_in_user` - залогиниваем пользователя `@user`. Создаём (или изменяем существующие) объекты с этим пользователем (`@user`) и с другим. Тестируем.

2017-05-25 21:30 UTC, webmstk commented on app/models/user.rb
> +  has_many :answers, dependent: :destroy
Здесь важно подумать, действительно ли нужно удалять все оставленные пользователем ответы при его удалении. Не ошибка, такой вариант приемлем :)

2017-05-26 04:52 UTC, merged