Lesson7
bagdenia/qna pull request #6
Opened 2017-06-04 17:38 UTC by bagdenia

2017-06-04 19:38 UTC, palkan-th requested changes

2017-06-04 19:38 UTC, palkan-th commented on app/models/answer.rb
> +    question.answers.update_all(best: false)
Здесь один важный момент: сейчас у тебя операция выбора лучшего ответа состоит из двух запросов, но нет гарантии, что оба выполнятся (например, после первого может произойти какая-то ошибка и второй запрос упадёт). Значит, возможно нарушение согласованности данных (у нас был лучший ответ, мы выбрали новый, а в результате ни одного не осталось).

Нужно сделать эту операцию атомарной, используя возможности БД.

2017-06-04 19:38 UTC, palkan-th commented on db/migrate/20170531201354_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean, default: false
`null: false`

2017-06-04 19:38 UTC, palkan-th commented on spec/acceptance/delete_answer_spec.rb
> +    sleep(1)
????

2017-06-04 19:38 UTC, palkan-th commented on spec/acceptance/edit_answer_spec.rb
> +      sleep(1)
`sleep` в тестах нельзя использовать: во-первых, это лишнее время (1 секунда – это много), во-вторых, это время недетерминировано, при других условиях оно может быть и больше, тогда тесты упадут.

Асинхронное выполнение можно контролировать с помощью матчеров `have_content`, `have_text`. В них встроено ожидание.

А какой в итоге драйвер ты используешь? По-хорошему, должно работать вообще без всяких `sleep`.

Мы недавно, кстати, обсуждали похожую проблему http://connect.thinknetica.com/t/zanyatie-6-ajax-chast-1-voprosy-i-kommentarii/416/156

2017-06-04 19:38 UTC, palkan-th commented on spec/acceptance/set_best_spec.rb
> +      within "#answer-#{Answer.first.id}" do
Так делать нельзя.  У тебя `Answer.first` может вернуть что угодно, если не указан порядок. Кроме того, в базе могут быть другие ответы (если использовать `fixtures`, например).
Нужно оперировать только теми данными, которые ты сама создаёшь в тесте (в твоём случае это массив `answers`).

2017-06-04 19:38 UTC, palkan-th commented on spec/acceptance/set_best_spec.rb
> +  #   best_tr = page.find('.answr').first(:xpath, 'tr[1]')
Проблема в `find` в том, что он синхронный и не ждёт появления контента на странице, как это делают матчеры `have_...` (о которых я уже писал).

2017-06-04 20:23 UTC, bagdenia commented on spec/acceptance/edit_answer_spec.rb
> +      sleep(1)
сейчас selenium, возвращалась к нему, когда искала варианты решения траблов с тестами. ну да, если без слипов, то вижу в браузере что юзер не успевает авторизоваться и как итог совсем не ожидаемое видение страницы.

2017-06-04 20:24 UTC, bagdenia commented on spec/acceptance/set_best_spec.rb
> +      within "#answer-#{Answer.first.id}" do
а, ок

2017-06-04 20:25 UTC, bagdenia commented on spec/acceptance/set_best_spec.rb
> +  #   best_tr = page.find('.answr').first(:xpath, 'tr[1]')
но тут я хочу определить блок css в котором я  буду искать лучший ответ. как с помощью матчеров have я укажу что ожидаю видеть  BEST в первой строке таблицы? наверно упустила что-то, пойду еще почитаю.

2017-06-04 21:14 UTC, bagdenia commented on db/migrate/20170531201354_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean, default: false
а чем плох дефолт фолс?

2017-06-04 21:18 UTC, bagdenia commented on db/migrate/20170531201354_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean, default: false
или имеется в виду не вместо, а вдобавок к?

2017-06-05 08:48 UTC, palkan-th commented on db/migrate/20170531201354_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean, default: false
вдобавок, да

2017-06-05 08:54 UTC, palkan-th approved these changes

2017-06-05 08:54 UTC, palkan-th commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :best)
А зачем здесь `best`?

2017-06-05 08:54 UTC, palkan-th commented on app/models/answer.rb
> +      update(best: true)
Здесь нужно использовать `update!`, чтобы в случае ошибки валидации транзакция падала.

2017-06-05 08:54 UTC, palkan-th commented on spec/acceptance/answer_in_question_spec.rb
> +    expect(page).to have_link 'Log out'
Можно это добавить в хэлпер `sign_in`

2017-06-05 08:54 UTC, palkan-th commented on spec/acceptance/set_best_spec.rb
> +  #   best_tr = page.find('.answr').first(:xpath, 'tr[1]')
Тут надо использовать комбинацию `within` и `have...`:

```ruby
within "#table-answers tr:first-child" do
  expect(page).to have_content 'BEST'
end
```

С табличной вёрсткой не так удобно тестировать, как с блочной, много лишнего.

2017-06-05 09:01 UTC, bagdenia commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :best)
Недоразумение, пыталась от ошибок в тесте избавиться вновь вылезших. Уберу.

2017-06-05 09:01 UTC, bagdenia commented on app/models/answer.rb
> +      update(best: true)
ааа, хорошо, спасибо!

2017-06-05 09:02 UTC, bagdenia commented on spec/acceptance/answer_in_question_spec.rb
> +    expect(page).to have_link 'Log out'
кстати да, удобно.

2017-06-05 14:27 UTC, merged