Lesson9
bagdenia/qna pull request #8
Opened 2017-06-16 23:57 UTC by bagdenia

2017-06-17 08:18 UTC, palkan-th requested changes
Что-то у тебя тут коммиты со всех заданий подряд, давай-ка приведём всё в порядок.

2017-06-17 08:18 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +    respond_to do |format|
А зачем нам тут городить `respond_to` вообще? У нас один формат – JSON.

2017-06-17 08:18 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +    @votable = Class.const_get(vote_params[:votable_type]).find(vote_params[:votable_id])
А что будет, если пользователь передаст `votable_type`, которого у нас нет?

Лучше вложить этот ресурс в вопросы и ответы по отдельности (в роутах), и тогда можно будет использовать параметры пути по умолчанию и ограничить значения. В этом случае и `votable_id` и `votable_type` не надо будет передавать как пользовательский ввод, это будут параметры пути.

Подробнее смотри МК по консёрнам.

2017-06-17 08:18 UTC, palkan-th commented on app/models/user.rb
> +    votes.where('votable_type = ? and votable_id = ?', item.class.name, item.id).size > 0
Как-то сложно, не находишь?)

А вот если бы мы проверяли это не в пользователе, а в самом _votable_, было бы гораздо проще:

```ruby
def voted_by?(user)
  votes.where(user: user).exists?
end
```

И вообще, зачем нам всё это пихать в модель пользователя? Будет этакий  God Object. Это тяжело поддерживать и развивать.

Лучше всю логику, связанную с голосаванием, реализовать в консёрне Votable.

2017-06-17 08:18 UTC, palkan-th commented on app/models/vote.rb
> +  validates :elect, inclusion: [false, true]
Во-первых, зачем? У нас есть еще какое-то булево значение? (`nil` должен отсекаться на уровне базы).

Во-вторых, выбор в качестве типа голоса boolean не очень удобен. В будущем у нас может появится рейтинговая система, и голоса разных пользователей будут иметь разное значение. Поэтому удобнее использовать число.

Кроме того, для вычисления суммы голосов нам, опять же, числа удобней – просто берём сумму ("+" – это 1, "-" – это  -1).

2017-06-17 08:18 UTC, palkan-th commented on app/models/vote.rb
> +      klass = Class.const_get(votable_type)
Есть более короткая, рельсовая, запись: `votable_type.constantize`.

2017-06-17 08:18 UTC, palkan-th commented on app/models/vote.rb
> +  validate :self_vote_denied
Не нужно делать эту валидацию на уровне модели, это имеет отношение к _разрешению_ голосовать, а не к самим данным.

2017-06-17 22:25 UTC, bagdenia commented on app/models/user.rb
> +    votes.where('votable_type = ? and votable_id = ?', item.class.name, item.id).size > 0
Согласна, как-то вот не сообразила.

2017-06-17 22:33 UTC, bagdenia commented on app/controllers/votes_controller.rb
> +    @votable = Class.const_get(vote_params[:votable_type]).find(vote_params[:votable_id])
Я решила что удобнее не вкладывать, потому что видишь, у меня один паршл для голосов, и путь vote_path, а если вложить то исходя из типа опять переделывать путь, тот же гемор но с другой стороны. Или этого как-то можно избежать и я гоню? Обязательно вот это переделывать?

2017-06-17 22:34 UTC, bagdenia commented on app/models/vote.rb
> +  validates :elect, inclusion: [false, true]
Это да, спасибо.

2017-06-18 11:17 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +    @votable = Class.const_get(vote_params[:votable_type]).find(vote_params[:votable_id])
Можно избежать, используя [`polymorphic_path`](https://apidock.com/rails/ActionDispatch/Routing/PolymorphicRoutes/polymorphic_url), в рельсах всё уже придумано.

Передача типа ресурса в параметрах – это костыль, ломающий нам REST-архитектуру.
Работать будет, и, возможно, даже проще сделать сходу, но в будущем сложнее поддерживать (как минимум, из-за того, что нужно держать актуальным список допустимых `votable_type`).

2017-06-18 15:48 UTC, bagdenia commented on app/controllers/votes_controller.rb
> +    @votable = Class.const_get(vote_params[:votable_type]).find(vote_params[:votable_id])
Ок, поняла. Раз можно, переделаю. Спасибо.

2017-06-19 12:02 UTC, palkan-th approved these changes

2017-06-19 12:02 UTC, palkan-th commented on app/assets/javascripts/answers.js.coffee
> +    $('.answr').append(JST["templates/test"]({world: "World"}))
?

2017-06-19 12:02 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +    # binding.pry
?

2017-06-19 12:02 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +    @votable = @vote.votable_type.classify.constantize.find(@vote.votable_id)
Просто ж `@vote.votable`

2017-06-19 12:02 UTC, palkan-th commented on app/controllers/votes_controller.rb
> +      # binding.pry
?

2017-06-19 12:02 UTC, palkan-th commented on app/models/concerns/votable.rb
> +  def voted_by(user)
Правильнее добавлять "?" к методам-предикатам: `voted_by?(user)`

2017-06-19 12:54 UTC, bagdenia commented on app/assets/javascripts/answers.js.coffee
> +    $('.answr').append(JST["templates/test"]({world: "World"}))
это я знакомилась ) уберу

2017-06-19 12:54 UTC, bagdenia commented on app/controllers/votes_controller.rb
> +    @votable = @vote.votable_type.classify.constantize.find(@vote.votable_id)
мдаа... увлеклась

2017-06-29 21:49 UTC, closed without merging